name: RyzenTuner CI for debug build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [ Debug ]
        platform: [ x64 ]

    runs-on: windows-latest
    
    env:
      Solution_Name: RyzenTuner.sln
      Project_Name: RyzenTuner

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Initialization environment variables
        working-directory: ./openwrt
        run: |
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore Packages
        run: nuget restore $env:Solution_Name
  
      - name: Build
        run: msbuild $env:Solution_Name

      - name: Install packages
        run: |
          choco install wget --no-progress
          choco install unzip --no-progress

      - name: Add dependencies
        run: |
          wget -O libryzenadj-win64.zip https://github.com/FlyGoat/RyzenAdj/releases/download/v0.11.1/libryzenadj-win64.zip
          unzip libryzenadj-win64.zip
          cp build/libryzenadj.dll ./bin/Debug
          cp win32/inpoutx64.dll ./bin/Debug
          cp win32/WinRing0x64.dll ./bin/Debug
          cp win32/WinRing0x64.sys ./bin/Debug

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: RyzenTuner_${{ env.FILE_DATE }}
          path: "./bin/Debug"