name: RyzenTuner CI for debug build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [ Debug ]
        platform: [ x64, x86 ]

    runs-on: windows-latest
    
    env:
      Solution_Name: RyzenTuner.sln
      Project_Name: RyzenTuner

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

      - name: Restore Packages
        run: nuget restore $env:Solution_Name

      - name: Build
        run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: $env:Project_Name
          path: "."     